### ISSUE TITLE
Microsoft Edge 内核是 98版本的chrome 用了此插件还是不行😭

### ISSUE THREAD

**Issue by ZililuYa** [chirpmonster/chrome-cookie-extence#1]
Microsoft Edge 内核是 98版本的chrome 用了此插件还是不行😭

**Comment by ZililuYa** [comment]
![image](https://user-images.githubusercontent.com/24806758/150897651-210902ca-4703-4c15-9228-b0c9b4f44056.png)

**Comment by chirpmonster** [comment]
如果需要可以联系我qq598033121看一下
