### ISSUE TITLE
Unchecked runtime.lastError: Invalid header specification '{"name":"Cookie"}'.

### ISSUE THREAD

**Issue by YeWills** [chirpmonster/chrome-cookie-extence#2]
上个月还可以正常工作，现在就报错了， 谷歌版本：98.0.4758.102

Unchecked runtime.lastError: Invalid header specification '{"name":"Cookie"}'.
上下文
_generated_background_page.html
堆叠追踪
_generated_background_page.html:0 (匿名函数)

**Comment by chirpmonster** [comment]
如果需要可以联系我qq598033121看一下

**Comment by xenera-zhangtao** [comment]
我也遇到同样的问题，请问怎么解决。加你QQ了还没通过
