### ISSUE TITLE
manifest V3.0 不再支持 chrome.webRequest 进行请求拦截

### ISSUE THREAD

**Issue by GitYanwu** [chirpmonster/chrome-cookie-extence#4]
manifest V3.0 不再支持 chrome.webRequest 进行请求拦截，无法通过阻塞请求的方式修改请求头，请问下V3.0的版本应该怎么解决这个问题？

**Comment by chirpmonster** [comment]
V3新的API chrome.declarativeNetRequest 提供了modifyHeaders的功能，所以可以解决这个问题
https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#updating-enabled-rulesets
但是架构需要大幅度重构
目前所在的新的公司没有这个问题，所以可能不会跟进
